'use strict';
const KEY='trocki_vitanex_full_v1';const $=s=>document.querySelector(s);const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const today=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const defaults={reminders:[['08:00','💧','Su iç (200 ml)','sağlık'],['10:00','💊','İlaç hatırlatıcısı','ilaç'],['12:00','🍽️','Öğle yemeği','beslenme'],['15:00','📖','Kitap oku (15 dk)','eğitim']],tasks:[],finance:[],notes:[],moduleRecords:[],favorites:[],checks:{}};
let data;try{data=JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch{data=JSON.parse(JSON.stringify(defaults))}for(let k in defaults)if(!(k in data))data[k]=structuredClone(defaults[k]);data.reminders=data.reminders.map(x=>Array.isArray(x)?{id:uid(),time:x[0],icon:x[1],name:x[2],category:x[3]}:x);let page='home',plants=[],query='',onlyFav=false,detailId=null;const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(data))}catch{toast('Kayıt alanı dolu; yedek alın')}};persist();
function toast(s){let t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function completed(id){return !!data.checks[today()+':'+id]}function doneToggle(id){let key=today()+':'+id;data.checks[key]=!data.checks[key];persist();render()}
function nav(p){page=p;query='';detailId=null;$('#drawer').hidden=true;render();scrollTo(0,0)}
const tiles=[['❤️','Sağlık','health'],['🚶','Yürüyüş','walk'],['🍽️','Beslenme','nutrition'],['💰','Finans','finance'],['✅','Görevler','tasks'],['📘','Eğitim','education'],['📊','İstatistikler','stats'],['👥','Sosyal Yaşam','social'],['🌱','Kişisel Gelişim','personal'],['💼','İş / Kariyer','career'],['📄','Raporlar','reports'],['☁️','Yedekleme','backup'],['⚙️','Ayarlar','settings'],['🌿','Şifalı Bitkiler','plants']];
function reminderRows(list){return list.length?list.map(r=>`<div class="reminder ${completed(r.id)?'done':''}"><button class="check" data-action="toggle" data-id="${safe(r.id)}" aria-label="Tamamlandı">${completed(r.id)?'✓':''}</button><span class="time">${safe(r.time)}</span><span>${safe(r.icon||'🔔')}</span><span class="name">${safe(r.name)}</span><button class="link" data-action="edit" data-id="${safe(r.id)}">⋯</button></div>`).join(''):'<div class="empty">Henüz kayıt yok.</div>'}
function home(){let count=data.reminders.filter(r=>completed(r.id)).length;let total=data.reminders.length;let net=data.finance.reduce((s,x)=>s+(Number(x.amount)||0),0);let date=new Intl.DateTimeFormat('tr-TR',{dateStyle:'full'}).format(new Date());return `<div class="hero"><h1>İyi günler Troçki</h1><p>Bugün de kendin için güzel bir adım at. Daha sağlıklı, daha dengeli, daha üretken bir yaşam mümkün...</p><small>${safe(date)}</small></div><div class="summary"><div class="stat"><div class="emoji">❤️</div><strong>Sağlık</strong><b>${total?Math.round(count/total*100):0}%</b><small>Hatırlatıcılar</small></div><div class="stat"><div class="emoji">💰</div><strong>Finans</strong><b>${net.toLocaleString('tr-TR',{maximumFractionDigits:0})} ₺</b><small>Net kayıt</small></div><div class="stat"><div class="emoji">✅</div><strong>Görev</strong><b>${count}/${total}</b><small>Tamamlandı</small></div></div><div class="tiles">${tiles.map(x=>`<button class="tile" data-page="${x[2]}"><span>${x[0]}</span>${x[1]}</button>`).join('')}</div><div class="panel"><div class="row between"><h2>Bugünün Hatırlatıcıları</h2><button class="link" data-page="tasks">Tümünü Gör ›</button></div>${reminderRows([...data.reminders].sort((a,b)=>a.time.localeCompare(b.time)))}</div><div class="footer">VİTANEX · TROÇKİ® tarafından geliştirildi</div>`}
function heading(title,desc=''){return `<div class="heading"><h1>${title}</h1><p>${desc}</p></div>`}
function reminderPage(){return heading('💊 İlaçlar ve Hatırlatıcılar','Kayıtlar bu cihazda saklanır. İlaç adları ve dozları kendi reçetene göre girilmelidir.')+`<div class="buttons"><button class="btn" data-action="add">+ Hatırlatıcı Ekle</button></div><div class="panel">${reminderRows([...data.reminders].sort((a,b)=>a.time.localeCompare(b.time)))}</div><div class="notice">İlaç saatinde uygulama kapalıyken güvenilir bildirim göndermek için sunucu tabanlı bildirim sistemi gerekir. Bu sürüm yalnızca uygulama açıkken uyarı verebilir.</div>`}
function plantsPage(){let filtered=plants.filter(x=>(x.name+' '+x.latin+' '+x.use).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))&&(!onlyFav||data.favorites.includes(x.id)));let d=plants.find(x=>x.id===detailId);if(d)return `${heading(d.emoji+' '+safe(d.name),safe(d.latin))}<div class="panel detail"><h2>Bitki bilgisi</h2><p><b>Kullanılan kısmı:</b> ${safe(d.part)}</p><p><b>Geleneksel kullanım / kanıt:</b> ${safe(d.use)}</p><div class="notice"><b>⚠️ Güvenlik:</b> ${safe(d.warning)}</div><p class="muted">Bu rehber tanı, tedavi veya doz önerisi değildir. İlaç kullanıyorsan bitkisel ürünleri doktor veya eczacıya danışmadan başlatma.</p><div class="buttons"><button class="btn" data-action="fav" data-id="${d.id}">${data.favorites.includes(d.id)?'★ Favoriden çıkar':'☆ Favoriye ekle'}</button><button class="btn alt" data-action="plantback">← Bitkilere dön</button></div></div>`;return heading('🌿 Şifalı Bitkiler Rehberi',`${plants.length} bitki • Türkçe ve bilimsel adları • Geleneksel kullanım • Güvenlik uyarıları`)+`<div class="notice">⚠️ Bitkiler ilaçların yerine geçmez. Özellikle kan sulandırıcı, tansiyon, kalp ve antidepresan ilaçlarla ciddi etkileşimler olabilir.</div><input class="search" id="plantSearch" placeholder="Bitki adı ara..." value="${safe(query)}"><div class="buttons"><button class="chip ${!onlyFav?'active':''}" data-action="allplants">Tüm bitkiler (${plants.length})</button><button class="chip ${onlyFav?'active':''}" data-action="onlyfav">★ Favoriler (${data.favorites.length})</button></div><div class="plants" id="plantList">${filtered.map(x=>plantCard(x)).join('')||'<div class="empty">Bitki bulunamadı.</div>'}</div>`}
function plantCard(x){return `<div class="plant"><div class="symbol">${x.emoji}</div><div class="info"><strong>${safe(x.name)}</strong><em>${safe(x.latin)}</em><p>${safe(x.use)}</p><button class="link" data-action="detail" data-id="${x.id}">Bilgileri incele ›</button></div><button class="fav" data-action="fav" data-id="${x.id}" aria-label="Favori">${data.favorites.includes(x.id)?'★':'☆'}</button></div>`}
const moduleDefs={
 health:{title:'❤️ Sağlık',desc:'Tansiyon, nabız, oksijen ve sağlık kayıtların.',fields:[['systolic','Büyük tansiyon','number'],['diastolic','Küçük tansiyon','number'],['pulse','Nabız (atım/dk)','number'],['oxygen','SpO₂ (%)','number'],['detail','Açıklama','text']]},
 nutrition:{title:'🍽️ Beslenme',desc:'Öğünlerini, su tüketimini ve beslenme alışkanlıklarını izle.',fields:[['meal','Öğün / besin','text'],['water','Su (ml)','number'],['detail','Açıklama','text']]},
 education:{title:'📘 Eğitim',desc:'Kitaplar, okuma süresi ve öğrenme kayıtları.',fields:[['title','Kitap / konu','text'],['minutes','Okuma / çalışma (dk)','number'],['detail','Not','text']]},
 social:{title:'👥 Sosyal Yaşam',desc:'Etkinlikler, görüşmeler ve sosyal planların.',fields:[['title','Etkinlik / görüşme','text'],['place','Yer','text'],['detail','Not','text']]},
 personal:{title:'🌱 Kişisel Gelişim',desc:'Hedefler, alışkanlıklar ve günlük ilerleme.',fields:[['title','Hedef / alışkanlık','text'],['progress','İlerleme (%)','number'],['detail','Not','text']]},
 career:{title:'💼 İş / Kariyer',desc:'Projeler, iş planları ve çalışma saatleri.',fields:[['title','Proje / iş','text'],['hours','Çalışma süresi (saat)','number'],['detail','Not','text']]}
};
function modulePage(){const def=moduleDefs[page],items=(data.moduleRecords||[]).filter(x=>x.category===page).sort((a,b)=>b.date.localeCompare(a.date));const numeric=def.fields.filter(x=>x[2]==='number');return heading(def.title,def.desc)+`<div class="summary"><div class="stat"><strong>Toplam kayıt</strong><b>${items.length}</b></div><div class="stat"><strong>Bu ay</strong><b>${items.filter(x=>x.date.startsWith(today().slice(0,7))).length}</b></div><div class="stat"><strong>Son 7 gün</strong><b>${items.filter(x=>new Date(x.date+'T12:00:00')>=new Date(Date.now()-7*86400000)).length}</b></div></div><div class="buttons"><button class="btn" data-action="addmodule">+ Yeni Kayıt</button>${page==='health'?'<button class="btn alt" data-page="meds">💊 İlaçlar</button><button class="btn alt" data-page="walk">🚶 Yürüyüş</button>':''}<button class="btn alt" data-page="reports">📊 Raporlar</button></div>${numeric.length?`<div class="panel"><h2>📈 Ölçüm özeti</h2>${numeric.map(([key,label])=>{const nums=items.map(x=>Number(x.values[key])).filter(x=>Number.isFinite(x)&&x>0);return `<div class="reminder"><span class="name">${label}</span><b>${nums.length?(nums.reduce((a,b)=>a+b,0)/nums.length).toLocaleString('tr-TR',{maximumFractionDigits:1}):'—'}</b></div>`}).join('')}<small class="muted">Girilen değerlerin ortalamasıdır; tıbbi değerlendirme değildir.</small></div>`:''}<div class="panel"><h2>📅 Kayıt geçmişi</h2>${items.map(x=>`<div class="record"><div class="row between"><b>${safe(x.date)}</b><button class="link" data-action="delmodule" data-id="${safe(x.id)}">Sil</button></div>${def.fields.filter(([key])=>x.values[key]).map(([key,label])=>`<p><b>${label}:</b> ${safe(x.values[key])}</p>`).join('')}</div>`).join('')||'<div class="empty">Henüz kayıt yok. Yeni Kayıt ile başlayabilirsin.</div>'}</div>`}
function addModule(){const def=moduleDefs[page],category=page;form('Yeni kayıt · '+def.title,field('date','Tarih','date',today())+def.fields.map(([key,label,type])=>field(key,label,type,'',false)).join(''),fd=>{let values={};def.fields.forEach(([key])=>values[key]=String(fd.get(key)||'').trim());if(!Object.values(values).some(Boolean))return;data.moduleRecords??=[];data.moduleRecords.push({id:uid(),category,date:fd.get('date'),values})})}
function walkPage(){let rec=[];try{rec=JSON.parse(localStorage.getItem('vitanex_walks_v1')||'[]')}catch{}if(!Array.isArray(rec))rec=[];let km=rec.reduce((a,x)=>a+(Number(x.meters)||0),0)/1000;let steps=rec.reduce((a,x)=>a+(Number(x.steps)||0),0);return heading('🚶 Yürüyüş ve Aktivite','GPS mesafesi, tahmini adım sayısı, süre ve yürüyüş raporları.')+`<div class="summary"><div class="stat"><strong>Yürüyüş</strong><b>${rec.length}</b></div><div class="stat"><strong>Toplam km</strong><b>${km.toLocaleString('tr-TR',{maximumFractionDigits:2})}</b></div><div class="stat"><strong>Adım</strong><b>${steps.toLocaleString('tr-TR')}</b></div></div><div class="panel"><h2>🚶 Yürüyüşü başlat</h2><p>Yürüyüşe çıkarken takip ekranını aç. GPS konum izni vererek mesafeni ölçebilirsin.</p><a class="btn btnlink" href="./yuruyus.html">▶ Yürüyüş Takibini Aç</a></div><div class="notice">Adım sayısı GPS mesafesinden tahmin edilir. Safari arka planda konum takibini sürdüremeyebilir.</div>`}
function generic(){let m={health:['❤️ Sağlık','Sağlık notlarını ve ilaç hatırlatıcılarını takip et.'],nutrition:['🍽️ Beslenme','Günlük beslenme notlarını kaydet.'],education:['📘 Eğitim','Okuma ve öğrenme notları.'],social:['👥 Sosyal Yaşam','Sosyal etkinlik notları.'],personal:['🌱 Kişisel Gelişim','Hedef ve gelişim notları.'],career:['💼 İş / Kariyer','İş ve proje notları.']};let a=m[page];let notes=data.notes.filter(n=>n.category===page);return heading(a[0],a[1])+`<button class="btn" data-action="note">+ Yeni Not</button><div class="panel">${notes.map(n=>`<div class="reminder"><span class="name">${safe(n.text)}</span><button class="link" data-action="delnote" data-id="${safe(n.id)}">Sil</button></div>`).join('')||'<div class="empty">Henüz not eklenmedi.</div>'}</div>`}
function finance(){return heading('💰 Finans','Gelir ve gider kayıtları cihazda saklanır.')+`<button class="btn" data-action="addfinance">+ Gelir / Gider</button><div class="panel"><h2>Net: ${data.finance.reduce((s,x)=>s+Number(x.amount),0).toLocaleString('tr-TR',{style:'currency',currency:'TRY'})}</h2>${data.finance.map(x=>`<div class="reminder"><span class="name">${safe(x.title)}<br><small>${safe(x.date)}</small></span><strong>${Number(x.amount).toLocaleString('tr-TR')} ₺</strong><button class="link" data-action="delfinance" data-id="${safe(x.id)}">Sil</button></div>`).join('')||'<div class="empty">Henüz finans kaydı yok.</div>'}</div>`}
function stats(){let keys=Object.keys(data.checks).filter(k=>data.checks[k]);let n=data.reminders.length;return heading('📊 İstatistikler','İlaç ve hatırlatıcı tamamlama özeti.')+`<div class="summary"><div class="stat"><strong>Bugün</strong><b>${data.reminders.filter(r=>completed(r.id)).length}/${n}</b></div><div class="stat"><strong>Tüm kayıtlar</strong><b>${keys.length}</b></div><div class="stat"><strong>Bitki favori</strong><b>${data.favorites.length}</b></div></div><div class="panel"><h2>Son 7 gün</h2>${Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-6+i);let key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;let count=keys.filter(k=>k.startsWith(key+':')).length;return `<div class="reminder"><span class="name">${safe(key)}</span><b>${count} tamamlandı</b></div>`}).join('')}</div>`}
function reports(){let records=data.moduleRecords||[],walks=[];try{walks=JSON.parse(localStorage.getItem('vitanex_walks_v1')||'[]')}catch{};return heading('📄 Raporlar','Kayıtlarını görüntüle ve yedekle.')+`<div class="panel"><h2>📋 Bölüm kayıtları</h2>${Object.entries(moduleDefs).map(([k,v])=>`<div class="reminder"><span class="name">${v.title}</span><b>${records.filter(x=>x.category===k).length}</b></div>`).join('')}<div class="reminder"><span class="name">🚶 Yürüyüş</span><b>${Array.isArray(walks)?walks.length:0}</b></div></div>`+stats().replace(/<div class="heading">[\s\S]*?<\/div>/,'')+`<div class="buttons"><button class="btn" data-action="export">JSON Yedek İndir</button><button class="btn alt" data-page="backup">Yedeklemeye Git</button></div>`}
function backup(){return heading('☁️ Yedekleme','Kayıtlar bu cihazın tarayıcısında tutulur. Tarayıcı verileri silinirse kaybolabilir.')+`<div class="panel"><h2>Verilerini koru</h2><p>Yedek indirerek kayıtlarını başka cihaza taşıyabilirsin.</p><div class="buttons"><button class="btn" data-action="export">⬇ Yedek İndir</button><label class="btn alt" for="importFile">⬆ Yedek Yükle</label><input type="file" id="importFile" accept="application/json,.json" hidden></div></div>`}
function settings(){return heading('⚙️ Ayarlar','VİTANEX kişisel kullanım ayarları.')+`<div class="panel"><h2>Bildirimler</h2><p class="muted">Uygulama açıkken tarayıcı izin verirse hatırlatıcı uyarısı gösterilebilir. iPhone'da kapalı uygulama için sunucu Web Push gerekir.</p><button class="btn" data-action="notify">Bildirim İzni İste</button></div><div class="panel"><h2>Veri yönetimi</h2><button class="btn" data-page="backup">Yedekleme</button></div>`}
function render(){let content=page==='home'?home():page==='walk'?walkPage():moduleDefs[page]?modulePage():page==='plants'?plantsPage():page==='meds'||page==='tasks'?reminderPage():page==='finance'?finance():page==='stats'?stats():page==='reports'?reports():page==='backup'?backup():page==='settings'?settings():generic();$('#view').innerHTML=content;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#bellCount').textContent=data.reminders.filter(r=>!completed(r.id)).length||''}
function form(title,fields,submit){$('#drawer').hidden=false;$('#drawer').innerHTML=`<div class="inner"><div class="row between"><h2>${title}</h2><button class="btn alt" id="closeDrawer">✕ Kapat</button></div><form id="entryForm">${fields}<div class="buttons"><button class="btn" type="submit">Kaydet</button></div></form></div>`;$('#closeDrawer').onclick=()=>$('#drawer').hidden=true;$('#entryForm').onsubmit=e=>{e.preventDefault();submit(new FormData(e.currentTarget));$('#drawer').hidden=true;persist();render();toast('Kaydedildi')}}
const field=(name,label,type='text',value='',required=true)=>`<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${safe(value)}" ${required?'required':''}></div>`;
function addReminder(id){let r=data.reminders.find(x=>x.id===id);form(r?'Hatırlatıcı Düzenle':'Yeni Hatırlatıcı',field('name','İlaç / Hatırlatıcı Adı','text',r?.name)+field('time','Saat','time',r?.time||'09:00')+`<div class="field"><label>Kategori</label><select name="category"><option value="ilaç">💊 İlaç</option><option value="sağlık">❤️ Sağlık</option><option value="beslenme">🍽️ Beslenme</option><option value="eğitim">📘 Eğitim</option><option value="diğer">🔔 Diğer</option></select></div>${r?'<button type="button" class="btn danger" id="removeEntry">Hatırlatıcıyı Sil</button>':''}`,fd=>{let cat=fd.get('category');let entry={id:id||uid(),name:fd.get('name').trim(),time:fd.get('time'),category:cat,icon:({ilaç:'💊',sağlık:'❤️',beslenme:'🍽️',eğitim:'📘',diğer:'🔔'})[cat]};if(r)Object.assign(r,entry);else data.reminders.push(entry)});if(r){$('#entryForm select').value=r.category;$('#removeEntry').onclick=()=>{if(confirm('Hatırlatıcı silinsin mi?')){data.reminders=data.reminders.filter(x=>x.id!==id);persist();$('#drawer').hidden=true;render()}}}}
function addNote(){form('Yeni Not',`<div class="field"><label>Not</label><textarea name="text" required></textarea></div>`,fd=>data.notes.push({id:uid(),category:page,text:fd.get('text')}))}
function addFinance(){form('Gelir / Gider',field('title','Açıklama')+field('amount','Tutar (gider için eksi yaz)','number')+field('date','Tarih','date',today()),fd=>data.finance.push({id:uid(),title:fd.get('title'),amount:Number(fd.get('amount')),date:fd.get('date')}))}
function exportData(){let blob=new Blob([JSON.stringify({format:'TROCKI-VITANEX',version:1,exported:new Date().toISOString(),data,walks:JSON.parse(localStorage.getItem('vitanex_walks_v1')||'[]'),walkSettings:JSON.parse(localStorage.getItem('vitanex_walk_settings_v1')||'{}')},null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='VITANEX-yedek-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function drawerMenu(){let d=$('#drawer');d.hidden=false;d.innerHTML=`<div class="inner"><div class="row between"><h2>VİTANEX Menü</h2><button class="btn alt" id="closeDrawer">✕</button></div>${[['⌂','Ana Sayfa','home'],['💊','İlaçlar / Hatırlatıcılar','meds'],...tiles].map(x=>`<button class="nav" data-page="${x[2]}">${x[0]} ${x[1]}</button>`).join('')}</div>`;$('#closeDrawer').onclick=()=>d.hidden=true}
document.addEventListener('click',e=>{let b=e.target.closest('[data-page],[data-action]');if(!b)return;if(b.dataset.page){nav(b.dataset.page);return}let a=b.dataset.action,id=b.dataset.id;if(a==='toggle')doneToggle(id);if(a==='add')addReminder();if(a==='edit')addReminder(id);if(a==='detail'){detailId=Number(id);render();scrollTo(0,0)}if(a==='plantback'){detailId=null;render()}if(a==='fav'){let n=Number(id);data.favorites=data.favorites.includes(n)?data.favorites.filter(x=>x!==n):[...data.favorites,n];persist();render()}if(a==='allplants'){onlyFav=false;render()}if(a==='onlyfav'){onlyFav=true;render()}if(a==='addmodule')addModule();if(a==='delmodule'){if(confirm('Bu kayıt silinsin mi?')){data.moduleRecords=(data.moduleRecords||[]).filter(x=>x.id!==id);persist();render()}}if(a==='note')addNote();if(a==='delnote'){data.notes=data.notes.filter(x=>x.id!==id);persist();render()}if(a==='addfinance')addFinance();if(a==='delfinance'){data.finance=data.finance.filter(x=>x.id!==id);persist();render()}if(a==='export')exportData();if(a==='notify'){if(!('Notification'in window))toast('Bu tarayıcı desteklemiyor');else Notification.requestPermission().then(x=>toast('Bildirim izni: '+x))}});
document.addEventListener('input',e=>{if(e.target.id==='plantSearch'){query=e.target.value;let filtered=plants.filter(x=>(x.name+' '+x.latin+' '+x.use).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))&&(!onlyFav||data.favorites.includes(x.id)));$('#plantList').innerHTML=filtered.map(plantCard).join('')||'<div class="empty">Bitki bulunamadı.</div>'}});
document.addEventListener('change',async e=>{if(e.target.id!=='importFile'||!e.target.files[0])return;try{let obj=JSON.parse(await e.target.files[0].text());if(obj.format!=='TROCKI-VITANEX'||!obj.data||!Array.isArray(obj.data.reminders)||!Array.isArray(obj.data.favorites))throw Error('Geçersiz dosya');if(!confirm('Mevcut kayıtların üzerine yedek yüklensin mi?'))return;data=obj.data;if(Array.isArray(obj.walks))localStorage.setItem('vitanex_walks_v1',JSON.stringify(obj.walks));if(obj.walkSettings&&typeof obj.walkSettings==='object')localStorage.setItem('vitanex_walk_settings_v1',JSON.stringify(obj.walkSettings));for(let k in defaults)if(!(k in data))data[k]=structuredClone(defaults[k]);persist();render();toast('Yedek yüklendi')}catch{toast('Yedek dosyası okunamadı')}});
$('#menuBtn').onclick=drawerMenu;$('#bellBtn').onclick=()=>nav('meds');$('#fab').onclick=()=>page==='finance'?addFinance():moduleDefs[page]?addModule():page==='walk'?location.assign('./yuruyus.html'):addReminder();
async function init(){try{let res=await fetch('plants.json');if(!res.ok)throw Error();plants=await res.json()}catch{plants=[];toast('Bitki listesi yüklenemedi')}render();if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});setInterval(()=>{let now=new Date();let hh=now.toTimeString().slice(0,5);let marker='alert:'+today()+':'+hh;let pending=data.reminders.filter(r=>r.time===hh&&!completed(r.id));if(pending.length&&!sessionStorage.getItem(marker)){sessionStorage.setItem(marker,'1');toast(pending.map(x=>x.name).join(', '));if('Notification'in window&&Notification.permission==='granted')new Notification('VİTANEX Hatırlatıcı',{body:pending.map(x=>x.name).join(', ')})}},30000)}init();
